// File generated by FlutterFire CLI.
// TODO: Replace with actual generated file from `flutterfire configure`

import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  // TODO: Replace these placeholder values with actual

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCneA4OO6dSK21cwtDknfEOLVynDZvunK0',
    appId: '1:152026825458:android:2b69859d916da5ae69466b',
    messagingSenderId: '152026825458',
    projectId: 'safegirls-75937',
    storageBucket: 'safegirls-75937.firebasestorage.app',
  );

  // Firebase project configuration from flutterfire configure

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo-HqpY1XW9vqwOIJARdQZYoD6iLyq7_o',
    appId: '1:152026825458:ios:d3ec92f64220c9a269466b',
    messagingSenderId: '152026825458',
    projectId: 'safegirls-75937',
    storageBucket: 'safegirls-75937.firebasestorage.app',
    iosBundleId: 'com.saferide.saferide',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfnFReU0oLn63vJzp7aCwIEUzM9cTbzE8',
    appId: '1:152026825458:web:0332749e2606bc9369466b',
    messagingSenderId: '152026825458',
    projectId: 'safegirls-75937',
    authDomain: 'safegirls-75937.firebaseapp.com',
    storageBucket: 'safegirls-75937.firebasestorage.app',
    measurementId: 'G-MRS5J2LR54',
  );

}